### ISSUE TITLE
error TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by santoshgistto** [DavideViolante/Angular2-Full-Stack#11] opened 2016-09-06 11:57 UTC
getting the the errors

ERROR in /home/mynameweb/Angular2-Express-Mongoose/node_modules/@angular/core/src/application_init.d.ts
[0] (16,18): error TS2304: Cannot find name 'Promise'.

can u please  @DavideViolante take a look

**Comment by DavideViolante** [comment] 2016-09-06 18:33
When do you receive this error? Everything works fine for me. Re-clone the repo and run the commands mentioned on readme.md to run the project.

If anyone else noticed this error please reply here.

**Comment by go4d1** [comment] 2016-09-06 18:54
![image](https://cloud.githubusercontent.com/assets/739802/18286615/9d6dcda2-7441-11e6-9f34-50d7d41d4258.png)
I get it also. I'm running it under terminal in WebStorm - It runs OK after the messages cease. I think there's a way of suppressing this 'talk'

**Comment by santoshgistto** [comment] 2016-09-06 19:18
@DavideViolante  getting the same what @go4d1  is getting

**Comment by DavideViolante** [comment] 2016-09-06 19:40
1. Do you both have the latest version of my project?
2. Do you receive these error after "npm start"?

- Try using this file: https://github.com/DavideViolante/Angular2-Express-Mongoose/blob/6cd98a6ef843e27632fc3fff2ce09bf73dcf2647/webpack.config.js
but delete line 3

**Comment by santoshgistto** [comment] 2016-09-07 05:54
@DavideViolante 
 1. yes
2 . yes
3. did, getting the same error

**Comment by DavideViolante** [comment] 2016-09-07 19:49
I cannot reproduce your error...
Please provide me as much info as possible about your environment:
- OS
- NodeJS version (node --version), I've 4.4.7
- npm version (npm --version), I've 3.10.6 ("npm install -g npm" to update your version)
- did you make any modification to the project?
Also make a Google search and look if you can find some solutions or similar errors.
@go4d1 did you try also using normal console or only Webstorm?

**Comment by santoshgistto** [comment] 2016-09-08 05:21
ok
 
os - ubuntu 14.04
Node veriosn - v6.4.0
npm version - 1.3.10
no there is no modification in the project

**Comment by DavideViolante** [comment] 2016-09-08 07:03
Please try to update your npm version using "npm install -g npm" and let me know.

**Comment by santoshgistto** [comment] 2016-09-08 07:09
@DavideViolante updated the version npm@3.10.6

**Comment by DavideViolante** [comment] 2016-09-08 08:02
I don't know. Try an older version of my project (maybe RC5) and tell me which one doesn't give you this error. You can download previous versions from here: https://github.com/DavideViolante/Angular2-Express-Mongoose/commits/master
You need to click on <> and download the zip.

**Comment by santoshgistto** [comment] 2016-09-08 08:06
@DavideViolante ok sure
can you plz send me mail on santosh.gistto@gmail.com i want  to ask you query via mail (its not related to this issue)

**Comment by santoshgistto** [comment] 2016-09-09 08:02
seems this is related with my machine issue install typing  $(npm bin)/typings install
from project and fixed the issue

**Comment by DavideViolante** [comment] 2016-09-10 13:59
Try latest version, but I don't think it affects your bug.

**Comment by wardgeene** [comment] 2016-09-13 11:51
Hi, I had the same errors appearing but after doing 'npm install' and then do 'npm start' everything is fine. Could it be something with the typings install that needs to run again after modifying .ts files? Just guessing here.

**Comment by DavideViolante** [comment] 2016-09-19 22:38
The project has been completely rebuilt using Angular CLI. Closing.

**Closed by DavideViolante** 2016-09-19 22:38 UTC
